ARG PYTHON_VERSION=3.12
ARG CONTAINER_VERSION=bookworm

FROM python:${PYTHON_VERSION}-slim-${CONTAINER_VERSION}
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000

# Setup user
RUN adduser --disabled-password --uid $USER_UID $USERNAME && \
    mkdir -p /etc/sudoers.d && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

# Install packages
RUN apt-get update && apt-get -y install sudo git openssh-client

